// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# The Apideck Lead API lets you create, read, update, delete and list leads across CRM integrations through Apideck Unify, using a single unified data model.
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config =  {}, string serviceUrl = "https://unify.apideck.com/lead") returns error? {
        http:ClientConfiguration httpClientConfig = {httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # List leads
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Leads 
    remote isolated function listLeads(ListLeadsHeaders headers, *ListLeadsQueries queries) returns GetLeadsResponse|error {
        string resourcePath = string `/leads`;
        map<Encoding> queryParamEncoding = {"filter": {style: DEEPOBJECT, explode: true}, "sort": {style: DEEPOBJECT, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Create lead
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Details of the lead to create 
    # + return - Lead created 
    remote isolated function createLead(CreateLeadHeaders headers, Lead payload, *CreateLeadQueries queries) returns CreateLeadResponse|error {
        string resourcePath = string `/leads`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get lead
    #
    # + id - ID of the record you are acting upon
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Lead 
    remote isolated function getLead(string id, GetLeadHeaders headers, *GetLeadQueries queries) returns GetLeadResponse|error {
        string resourcePath = string `/leads/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Delete lead
    #
    # + id - ID of the record you are acting upon
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Lead deleted 
    remote isolated function deleteLead(string id, DeleteLeadHeaders headers, *DeleteLeadQueries queries) returns DeleteLeadResponse|error {
        string resourcePath = string `/leads/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update lead
    #
    # + id - ID of the record you are acting upon
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Lead fields to update 
    # + return - Lead updated 
    remote isolated function updateLead(string id, UpdateLeadHeaders headers, Lead payload, *UpdateLeadQueries queries) returns UpdateLeadResponse|error {
        string resourcePath = string `/leads/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, httpHeaders);
    }
}
