// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/constraint;
import ballerina/data.jsondata;
import ballerina/http;

# A object containing a unique identifier for the resource that was created, updated, or deleted
public type UnifiedId record {
    # The unique identifier of the resource
    string id;
};

public type DeleteLeadResponse record {
    # HTTP Response Status Code
    @jsondata:Name {value: "status_code"}
    int statusCode;
    # A object containing a unique identifier for the resource that was created, updated, or deleted
    UnifiedId data;
    # Unified API resource name
    string 'resource;
    @jsondata:Name {value: "_raw"}
    Raw? raw?;
    # Apideck ID of service provider
    string 'service;
    # Operation performed
    string operation;
    # HTTP Response Status
    string status;
};

# Response metadata
public type Meta record {
    # Number of items returned in the data property of the response
    @jsondata:Name {value: "items_on_page"}
    int itemsOnPage?;
    # Cursors to navigate to previous or next pages through the API
    MetaCursors cursors?;
    # Number of records available in total for this resource
    @jsondata:Name {value: "total_count"}
    int totalCount?;
    # Non-fatal warnings emitted when optional workflow steps failed. Present only when at least one step degraded; the response status remains 200
    MetaWarnings[]? warnings?;
};

public type GetLeadResponse record {
    # HTTP Response Status Code
    @jsondata:Name {value: "status_code"}
    int statusCode;
    Lead data;
    # Unified API resource name
    string 'resource;
    @jsondata:Name {value: "_raw"}
    Raw? raw?;
    # Apideck ID of service provider
    string 'service;
    # Response metadata
    Meta meta?;
    # Operation performed
    string operation;
    # HTTP Response Status
    string status;
};

public type Email record {|
    # Unique identifier for the email address
    string? id?;
    # Email type
    "primary"|"secondary"|"work"|"personal"|"billing"|"other"? 'type?;
    # Email address
    string? email;
|};

# The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources
public type PassThroughBody PassThroughItem[];

public type Address record {|
    # country code according to ISO 3166-1 alpha-2
    string? country?;
    # Additional notes
    string? notes?;
    # The address string. Some APIs don't provide structured address data
    string? 'string?;
    # Name of city
    string? city?;
    # Latitude of the address
    string? latitude?;
    # Address field that holds a sublocality, such as a county
    string? county?;
    # The type of address
    "primary"|"secondary"|"home"|"office"|"shipping"|"billing"|"work"|"other"? 'type?;
    # Unique identifier for the address
    string? id?;
    # Name of state
    string? state?;
    # Line 3 of the address
    string? line3?;
    # Fax number of the address
    string? fax?;
    # Line 2 of the address
    string? line2?;
    # Line 1 of the address e.g. number, street, suite, apt #, etc
    string? line1?;
    # Email address of the address
    string? email?;
    # Longitude of the address
    string? longitude?;
    # Line 5 of the address
    string? line5?;
    # Name of the contact person at the address
    @jsondata:Name {value: "contact_name"}
    string? contactName?;
    # Website of the address
    string? website?;
    # Line 4 of the address
    string? line4?;
    @jsondata:Name {value: "row_version"}
    RowVersion? rowVersion?;
    # The name of the address
    string? name?;
    # Street number
    @jsondata:Name {value: "street_number"}
    string? streetNumber?;
    # Phone number of the address
    @jsondata:Name {value: "phone_number"}
    string? phoneNumber?;
    # Salutation of the contact person at the address
    string? salutation?;
    # Zip code or equivalent
    @jsondata:Name {value: "postal_code"}
    string? postalCode?;
|};

# Cursors to navigate to previous or next pages through the API
public type MetaCursors record {
    # Cursor to navigate to the next page of results through the API
    string? next?;
    # Cursor to navigate to the current page of results through the API
    string? current?;
    # Cursor to navigate to the previous page of results through the API
    string? previous?;
};

public type Website record {|
    # Unique identifier for the website
    string? id?;
    # The type of website
    "primary"|"secondary"|"work"|"personal"|"other"? 'type?;
    # The website URL
    @constraint:String {minLength: 1}
    string url;
|};

# Raw response from the integration when raw=true query param is provided
public type Raw record {
};

public type PassThroughItem_extend_paths record {|
    # JSONPath string specifying where to apply the value.
    string path;
    # The value to set at the specified path, can be any type.
    anydata value;
|};

public type GetLeadsResponse record {
    # HTTP Response Status Code
    @jsondata:Name {value: "status_code"}
    int statusCode;
    Lead[] data;
    # Unified API resource name
    string 'resource;
    @jsondata:Name {value: "_raw"}
    Raw? raw?;
    # Apideck ID of service provider
    string 'service;
    # Response metadata
    Meta meta?;
    # Links to navigate to previous or next pages through the API
    Links links?;
    # Operation performed
    string operation;
    # HTTP Response Status
    string status;
};

# Represents the Queries record for the operation: listLeads
public type ListLeadsQueries record {
    # Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response
    string? cursor?;
    # Apply filters
    LeadsFilter filter?;
    # Number of results to return. Minimum 1, Maximum 200, Default 20
    @constraint:Int {minValue: 1, maxValue: 200}
    int 'limit = 20;
    # Include raw response. Mostly used for debugging purposes
    boolean raw = false;
    # Apply sorting
    LeadsSort sort?;
    # The 'fields' parameter allows API users to specify the fields they want to include in the API response. If this parameter is not present, the API will return all available fields. If this parameter is present, only the fields specified in the comma-separated string will be included in the response. Nested properties can also be requested by using a dot notation. <br /><br />Example: `fields=name,email,addresses.city`<br /><br />In the example above, the response will only include the fields "name", "email" and "addresses.city". If any other fields are available, they will be excluded
    string? fields?;
};

public type LeadsFilter record {|
    # Name of the lead to filter on
    string name?;
    # Last name of the lead to filter on
    @jsondata:Name {value: "last_name"}
    string lastName?;
    # Phone number of the lead to filter on
    @jsondata:Name {value: "phone_number"}
    string phoneNumber?;
    # First name of the lead to filter on
    @jsondata:Name {value: "first_name"}
    string firstName?;
    # E-mail of the lead to filter on
    string email?;
|};

# The direction in which to sort the results
public type SortDirection "asc"|"desc";

# Represents the Headers record for the operation: createLead
public type CreateLeadHeaders record {
    # Secret API key sent as a bearer token, for example `Bearer YOUR_API_KEY`. Keep it out of client-side code
    @http:Header {name: "Authorization"}
    string authorization;
    # Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API
    @http:Header {name: "x-apideck-service-id"}
    string xApideckServiceId?;
    # ID of the consumer which you want to get or push data from
    @http:Header {name: "x-apideck-consumer-id"}
    string xApideckConsumerId;
    # The ID of your Unify application
    @http:Header {name: "x-apideck-app-id"}
    string xApideckAppId;
};

# Represents the Headers record for the operation: listLeads
public type ListLeadsHeaders record {
    # Secret API key sent as a bearer token, for example `Bearer YOUR_API_KEY`. Keep it out of client-side code
    @http:Header {name: "Authorization"}
    string authorization;
    # Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API
    @http:Header {name: "x-apideck-service-id"}
    string xApideckServiceId?;
    # ID of the consumer which you want to get or push data from
    @http:Header {name: "x-apideck-consumer-id"}
    string xApideckConsumerId;
    # The ID of your Unify application
    @http:Header {name: "x-apideck-app-id"}
    string xApideckAppId;
};

# Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)
public type Currency "UNKNOWN_CURRENCY"|"AED"|"AFN"|"ALL"|"AMD"|"ANG"|"AOA"|"ARS"|"AUD"|"AWG"|"AZN"|"BAM"|"BBD"|"BDT"|"BGN"|"BHD"|"BIF"|"BMD"|"BND"|"BOB"|"BOV"|"BRL"|"BSD"|"BTN"|"BWP"|"BYR"|"BZD"|"CAD"|"CDF"|"CHE"|"CHF"|"CHW"|"CLF"|"CLP"|"CNY"|"COP"|"COU"|"CRC"|"CUC"|"CUP"|"CVE"|"CZK"|"DJF"|"DKK"|"DOP"|"DZD"|"EGP"|"ERN"|"ETB"|"EUR"|"FJD"|"FKP"|"GBP"|"GEL"|"GHS"|"GIP"|"GMD"|"GNF"|"GTQ"|"GYD"|"HKD"|"HNL"|"HRK"|"HTG"|"HUF"|"IDR"|"ILS"|"INR"|"IQD"|"IRR"|"ISK"|"JMD"|"JOD"|"JPY"|"KES"|"KGS"|"KHR"|"KMF"|"KPW"|"KRW"|"KWD"|"KYD"|"KZT"|"LAK"|"LBP"|"LKR"|"LRD"|"LSL"|"LTL"|"LVL"|"LYD"|"MAD"|"MDL"|"MGA"|"MKD"|"MMK"|"MNT"|"MOP"|"MRO"|"MUR"|"MVR"|"MWK"|"MXN"|"MXV"|"MYR"|"MZN"|"NAD"|"NGN"|"NIO"|"NOK"|"NPR"|"NZD"|"OMR"|"PAB"|"PEN"|"PGK"|"PHP"|"PKR"|"PLN"|"PYG"|"QAR"|"RON"|"RSD"|"RUB"|"RWF"|"SAR"|"SBD"|"SCR"|"SDG"|"SEK"|"SGD"|"SHP"|"SLL"|"SOS"|"SRD"|"SSP"|"STD"|"SVC"|"SYP"|"SZL"|"THB"|"TJS"|"TMT"|"TND"|"TOP"|"TRC"|"TRY"|"TTD"|"TWD"|"TZS"|"UAH"|"UGX"|"USD"|"USN"|"USS"|"UYI"|"UYU"|"UZS"|"VEF"|"VND"|"VUV"|"WST"|"XAF"|"XAG"|"XAU"|"XBA"|"XBB"|"XBC"|"XBD"|"XCD"|"XDR"|"XOF"|"XPD"|"XPF"|"XPT"|"XTS"|"XXX"|"YER"|"ZAR"|"ZMK"|"ZMW"|"BTC"|"ETH"?;

public type Lead record {|
    Address[] addresses?;
    # The owner of the lead
    @jsondata:Name {value: "owner_id"}
    string? ownerId?;
    # The prefix of the lead
    string? prefix?;
    @jsondata:Name {value: "social_links"}
    SocialLink[] socialLinks?;
    # The source of the lead
    @jsondata:Name {value: "lead_source"}
    string? leadSource?;
    # The description of the lead
    string? description?;
    # Date created in ISO 8601 format
    @jsondata:Name {value: "created_at"}
    string? createdAt?;
    # language code according to ISO 639-1. For the United States - EN
    string? language?;
    # The monetary amount of the lead
    @jsondata:Name {value: "monetary_amount"}
    decimal? monetaryAmount?;
    # The contact the lead is associated with
    @jsondata:Name {value: "contact_id"}
    string? contactId?;
    # The job title of the lead
    string? title?;
    @jsondata:Name {value: "custom_mappings"}
    CustomMappings? customMappings?;
    Email[] emails?;
    # Date updated in ISO 8601 format
    @jsondata:Name {value: "updated_at"}
    string? updatedAt?;
    # Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)
    Currency? currency?;
    # Unique identifier for the contact
    string id?;
    # The fax number of the lead
    string? fax?;
    # The first name of the lead
    @jsondata:Name {value: "first_name"}
    string? firstName?;
    # The identifier of the lead
    @jsondata:Name {value: "lead_id"}
    string? leadId?;
    # The name of the owner of the lead
    @jsondata:Name {value: "owner_name"}
    string? ownerName?;
    # The company the lead is associated with
    @jsondata:Name {value: "company_id"}
    string? companyId?;
    @jsondata:Name {value: "custom_fields"}
    CustomField[]? customFields?;
    @jsondata:Name {value: "pass_through"}
    PassThroughBody passThrough?;
    # The last name of the lead
    @jsondata:Name {value: "last_name"}
    string? lastName?;
    Tags? tags?;
    @jsondata:Name {value: "phone_numbers"}
    PhoneNumber[] phoneNumbers?;
    # The name of the company the lead is associated with
    @jsondata:Name {value: "company_name"}
    string? companyName?;
    # Full name of the lead
    string name;
    Website[] websites?;
    string? status?;
|};

# When custom mappings are configured on the resource, the result is included here
public type CustomMappings record {
};

public type PassThroughItem record {|
    # Identifier for the service to which this pass_through should be applied
    @jsondata:Name {value: "service_id"}
    string serviceId;
    # Optional identifier for a workflow operation to which this pass_through should be applied. This is useful for Unify calls that are making more than one downstream request
    @jsondata:Name {value: "operation_id"}
    string operationId?;
    # Simple object allowing any properties for direct extension
    @jsondata:Name {value: "extend_object"}
    record {} extendObject?;
    # Array of objects for structured data modifications via paths
    @jsondata:Name {value: "extend_paths"}
    PassThroughItem_extend_paths[] extendPaths?;
|};

public type Tags string[]?;

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

# Represents the Headers record for the operation: getLead
public type GetLeadHeaders record {
    # Secret API key sent as a bearer token, for example `Bearer YOUR_API_KEY`. Keep it out of client-side code
    @http:Header {name: "Authorization"}
    string authorization;
    # Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API
    @http:Header {name: "x-apideck-service-id"}
    string xApideckServiceId?;
    # ID of the consumer which you want to get or push data from
    @http:Header {name: "x-apideck-consumer-id"}
    string xApideckConsumerId;
    # The ID of your Unify application
    @http:Header {name: "x-apideck-app-id"}
    string xApideckAppId;
};

# Represents the Queries record for the operation: deleteLead
public type DeleteLeadQueries record {
    # Include raw response. Mostly used for debugging purposes
    boolean raw = false;
};

# Represents the Headers record for the operation: deleteLead
public type DeleteLeadHeaders record {
    # Secret API key sent as a bearer token, for example `Bearer YOUR_API_KEY`. Keep it out of client-side code
    @http:Header {name: "Authorization"}
    string authorization;
    # Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API
    @http:Header {name: "x-apideck-service-id"}
    string xApideckServiceId?;
    # ID of the consumer which you want to get or push data from
    @http:Header {name: "x-apideck-consumer-id"}
    string xApideckConsumerId;
    # The ID of your Unify application
    @http:Header {name: "x-apideck-app-id"}
    string xApideckAppId;
};

# Represents the Queries record for the operation: createLead
public type CreateLeadQueries record {
    # Include raw response. Mostly used for debugging purposes
    boolean raw = false;
};

# Represents the Queries record for the operation: getLead
public type GetLeadQueries record {
    # Include raw response. Mostly used for debugging purposes
    boolean raw = false;
    # The 'fields' parameter allows API users to specify the fields they want to include in the API response. If this parameter is not present, the API will return all available fields. If this parameter is present, only the fields specified in the comma-separated string will be included in the response. Nested properties can also be requested by using a dot notation. <br /><br />Example: `fields=name,email,addresses.city`<br /><br />In the example above, the response will only include the fields "name", "email" and "addresses.city". If any other fields are available, they will be excluded
    string? fields?;
};

public type UpdateLeadResponse record {
    # HTTP Response Status Code
    @jsondata:Name {value: "status_code"}
    int statusCode;
    # A object containing a unique identifier for the resource that was created, updated, or deleted
    UnifiedId data;
    # Unified API resource name
    string 'resource;
    @jsondata:Name {value: "_raw"}
    Raw? raw?;
    # Apideck ID of service provider
    string 'service;
    # Operation performed
    string operation;
    # HTTP Response Status
    string status;
};

# Represents the Headers record for the operation: updateLead
public type UpdateLeadHeaders record {
    # Secret API key sent as a bearer token, for example `Bearer YOUR_API_KEY`. Keep it out of client-side code
    @http:Header {name: "Authorization"}
    string authorization;
    # Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API
    @http:Header {name: "x-apideck-service-id"}
    string xApideckServiceId?;
    # ID of the consumer which you want to get or push data from
    @http:Header {name: "x-apideck-consumer-id"}
    string xApideckConsumerId;
    # The ID of your Unify application
    @http:Header {name: "x-apideck-app-id"}
    string xApideckAppId;
};

public type LeadsSort record {|
    # The field on which to sort the Leads
    "created_at"|"updated_at"|"name"|"first_name"|"last_name"|"email" 'by?;
    # The direction in which to sort the results
    SortDirection direction?;
|};

# Represents the Queries record for the operation: updateLead
public type UpdateLeadQueries record {
    # Include raw response. Mostly used for debugging purposes
    boolean raw = false;
};

# A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object
public type RowVersion string?;

# Advisory warning emitted when an optional workflow step fails non-fatally. The overall request still succeeds (HTTP 200); inspect this to detect partial or degraded data
public type MetaWarnings record {
    # HTTP status code returned by the failed downstream request, when available
    @jsondata:Name {value: "status_code"}
    int? statusCode?;
    # Discriminator for the warning kind
    string 'type?;
    # Short error description from the downstream provider, when available
    string? 'error?;
    # Detailed message from the downstream provider, when available
    string? message?;
    # Identifier of the workflow step that failed
    string? operation?;
};

public type CreateLeadResponse record {
    # HTTP Response Status Code
    @jsondata:Name {value: "status_code"}
    int statusCode;
    # A object containing a unique identifier for the resource that was created, updated, or deleted
    UnifiedId data;
    # Unified API resource name
    string 'resource;
    @jsondata:Name {value: "_raw"}
    Raw? raw?;
    # Apideck ID of service provider
    string 'service;
    # Operation performed
    string operation;
    # HTTP Response Status
    string status;
};

public type CustomField anydata;

public type PhoneNumber record {|
    # The country code of the phone number, e.g. +1
    @jsondata:Name {value: "country_code"}
    string? countryCode?;
    # The phone number
    @constraint:String {minLength: 1}
    string number;
    # The extension of the phone number
    string? extension?;
    # The area code of the phone number, e.g. 323
    @jsondata:Name {value: "area_code"}
    string? areaCode?;
    # Unique identifier of the phone number
    string? id?;
    # The type of phone number
    "primary"|"secondary"|"home"|"work"|"office"|"mobile"|"assistant"|"fax"|"direct-dial-in"|"personal"|"billing"|"other"? 'type?;
|};

# Links to navigate to previous or next pages through the API
public type Links record {
    # Link to navigate to the previous page through the API
    string? next?;
    # Link to navigate to the current page through the API
    string current?;
    # Link to navigate to the previous page through the API
    string? previous?;
};

public type SocialLink record {|
    # Unique identifier of the social link
    string? id?;
    # Type of the social link, e.g. twitter
    string? 'type?;
    # URL of the social link, e.g. https://www.twitter.com/apideck
    @constraint:String {minLength: 1}
    string url;
|};
